name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master
jobs:
  maven-build:
    name: "${{ matrix.os }}, jdk-${{ matrix.jdk }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2022]
        jdk: [11, 17]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: "adopt"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  build-result:
    runs-on: ubuntu-latest
    needs: [maven-build]
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
      - name: Collect build result
        run: |
          if echo ${{ needs.maven-build.result }} | grep -E 'cancelled|failure' -o > null
          then
            echo "There are failed/cancelled builds"
            exit 1 
          else
            echo "All builds are successful/skipped"
            exit 0
          fi